server:
  port: 9999
spring:
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/bbs?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
#        password: 123456
#        password: 1234
        password: Leaves@1992
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

  http:

      encoding:
        force: true


  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8888

  #配置redis作为缓存
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
    password: Leaves@1992
    database: 0
  cache:
    type: redis

#消息队列配置
#  activemq:
#    user: admin
#    password: admin
#    broker-url: tcp://127.0.0.1:61616
#    pool:
#      enabled: true
#      max-connections: 10




logging:
  level:
      cc.ahxb.mapper: debug
  config: classpath:log4j2.yml

rm:
  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/

  sqlBak: ./bak/

  hostIP: 127.0.0.1

  dataBase: xb_framework

controllerReport: 1




