server:
  port: 8890
spring:
  datasource:
        url: jdbc:mysql://192.168.1.166:3306/aimijie?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
#        password: 123456
#        password: 1234
        password: Xbkj!123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

  http:

      encoding:
        force: true


  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8888

  #配置redis作为缓存
  redis:
    host: 192.168.1.166
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
    password: Xbkj!123456
    database: 0
  cache:
    type: redis

#消息队列配置
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10

mybatis:
  type-aliases-package: cc.ahxb.entity
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true


logging:
  level:
      cc.ahxb.mapper: debug
  config: classpath:log4j2.yml

rm:
  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/

  sqlBak: ./bak/

  hostIP: 192.168.1.166

  dataBase: aimijie

controllerReport: 1

#推送相关
push:
#推送AppKey
  appKey: 5c061f07f1f55648f00000d6
#推送appSecret
  appSecret: lwtt9vfauuwllfxfnpnddky4gdkns9i4

#消息队列的 queue 名称
queueName: publish.queue
#消息队列的 topic 名称
topicName: publish.topic




