package io.itman.model;

import io.itman.model.base.BaseApiCategories;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApiCategories extends BaseApiCategories<ApiCategories> {
	public static final ApiCategories dao = new ApiCategories().dao();
}
