package io.itman.model;

import io.itman.model.base.BaseApiContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApiContent extends BaseApiContent<ApiContent> {
	public static final ApiContent dao = new ApiContent().dao();
}
