package io.itman.model;

import io.itman.model.base.BaseContentcategories;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contentcategories extends BaseContentcategories<Contentcategories> {
	public static final Contentcategories dao = new Contentcategories().dao();
}
