package io.itman.model;

import io.itman.model.base.BaseDocumentContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DocumentContent extends BaseDocumentContent<DocumentContent> {
	public static final DocumentContent dao = new DocumentContent().dao();
}
