package io.itman.model;

import io.itman.model.base.BaseDocumentCategories;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DocumentCategories extends BaseDocumentCategories<DocumentCategories> {
	public static final DocumentCategories dao = new DocumentCategories().dao();
}
