package io.itman.model;

import io.itman.model.base.BaseErrorlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Errorlog extends BaseErrorlog<Errorlog> {
	public static final Errorlog dao = new Errorlog().dao();
}
