package io.itman.model;

import io.itman.model.base.BaseIpWhitelist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IpWhitelist extends BaseIpWhitelist<IpWhitelist> {
	public static final IpWhitelist dao = new IpWhitelist().dao();
}
