package io.itman.model;

import io.itman.model.base.BaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
	public static final Log dao = new Log().dao();
}
