package io.itman.model;

import io.itman.model.base.BaseMacWhitelist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MacWhitelist extends BaseMacWhitelist<MacWhitelist> {
	public static final MacWhitelist dao = new MacWhitelist().dao();
}
