package io.itman.model;

import io.itman.model.base.BaseProvincecitycounty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Provincecitycounty extends BaseProvincecitycounty<Provincecitycounty> {
	public static final Provincecitycounty dao = new Provincecitycounty().dao();
}
