package io.itman.model;

import io.itman.model.base.BaseSysAdministrator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAdministrator extends BaseSysAdministrator<SysAdministrator> {
	public static final SysAdministrator dao = new SysAdministrator().dao();
}
