package io.itman.model;

import io.itman.model.base.BaseSysAppversion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAppversion extends BaseSysAppversion<SysAppversion> {
	public static final SysAppversion dao = new SysAppversion().dao();
}
