package io.itman.model;

import io.itman.model.base.BaseSysButton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysButton extends BaseSysButton<SysButton> {
	public static final SysButton dao = new SysButton().dao();
	/*
判断菜单所包含按钮。0：不包含；1：已包含
*/
	private Integer contains;

	public Integer getContains() {
		return contains;
	}

	public void setContains(Integer contains) {
		this.contains = contains;
	}

	private Integer menuId;

	public Integer getMenuId() {
		return menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}
}
