package io.itman.model;

import io.itman.model.base.BaseSysBasicinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysBasicinfo extends BaseSysBasicinfo<SysBasicinfo> {
	public static final SysBasicinfo dao = new SysBasicinfo().dao();
}
