package io.itman.model;

import io.itman.model.base.BaseSysConnection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysConnection extends BaseSysConnection<SysConnection> {
	public static final SysConnection dao = new SysConnection().dao();
}
