package io.itman.model;

import io.itman.model.base.BaseSysJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysJob extends BaseSysJob<SysJob> {
	public static final SysJob dao = new SysJob().dao();
}
