package io.itman.model;

import io.itman.model.base.BaseSysMenubutton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenubutton extends BaseSysMenubutton<SysMenubutton> {
	public static final SysMenubutton dao = new SysMenubutton().dao();
	private String buttonName;

	private String buttonIcon;

	public String getButtonIcon() {
		return buttonIcon;
	}

	public void setButtonIcon(String buttonIcon) {
		this.buttonIcon = buttonIcon;
	}

	public String getButtonName() {
		return buttonName;
	}

	public void setButtonName(String buttonName) {
		this.buttonName = buttonName;
	}
}
