package io.itman.model;

import io.itman.model.base.BaseSysRolemenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRolemenu extends BaseSysRolemenu<SysRolemenu> {
	public static final SysRolemenu dao = new SysRolemenu().dao();
}
