package io.itman.model;

import io.itman.model.base.BaseSysSqlmodel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSqlmodel extends BaseSysSqlmodel<SysSqlmodel> {
	public static final SysSqlmodel dao = new SysSqlmodel().dao();
}
