package io.itman.model;

import io.itman.model.base.BaseSysSmstemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSmstemplate extends BaseSysSmstemplate<SysSmstemplate> {
	public static final SysSmstemplate dao = new SysSmstemplate().dao();
}
