package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRolemenu<M extends BaseSysRolemenu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
		return (M)this;
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public M setMenuId(java.lang.Integer menuId) {
		set("menuId", menuId);
		return (M)this;
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menuId");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
		return (M)this;
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}

	public M setButtonId(java.lang.String buttonId) {
		set("buttonId", buttonId);
		return (M)this;
	}
	
	public java.lang.String getButtonId() {
		return getStr("buttonId");
	}

	public M setValue(java.lang.Long value) {
		set("value", value);
		return (M)this;
	}
	
	public java.lang.Long getValue() {
		return getLong("value");
	}

}
