package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContent<M extends BaseContent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCategoriesId(java.lang.Integer categoriesId) {
		set("categoriesId", categoriesId);
		return (M)this;
	}
	
	public java.lang.Integer getCategoriesId() {
		return getInt("categoriesId");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setMainPicture(java.lang.String mainPicture) {
		set("mainPicture", mainPicture);
		return (M)this;
	}
	
	public java.lang.String getMainPicture() {
		return getStr("mainPicture");
	}

	public M setSoruce(java.lang.String soruce) {
		set("soruce", soruce);
		return (M)this;
	}
	
	public java.lang.String getSoruce() {
		return getStr("soruce");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setContents(java.lang.String contents) {
		set("contents", contents);
		return (M)this;
	}
	
	public java.lang.String getContents() {
		return getStr("contents");
	}

	public M setIsPublish(java.lang.Integer isPublish) {
		set("isPublish", isPublish);
		return (M)this;
	}
	
	public java.lang.Integer getIsPublish() {
		return getInt("isPublish");
	}

	public M setIsRec(java.lang.Integer isRec) {
		set("isRec", isRec);
		return (M)this;
	}
	
	public java.lang.Integer getIsRec() {
		return getInt("isRec");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setAddUserId(java.lang.Integer addUserId) {
		set("addUserId", addUserId);
		return (M)this;
	}
	
	public java.lang.Integer getAddUserId() {
		return getInt("addUserId");
	}

	public M setViewCount(java.lang.Integer viewCount) {
		set("viewCount", viewCount);
		return (M)this;
	}
	
	public java.lang.Integer getViewCount() {
		return getInt("viewCount");
	}

}
