package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setRequestData(java.lang.String requestData) {
		set("requestData", requestData);
		return (M)this;
	}
	
	public java.lang.String getRequestData() {
		return getStr("requestData");
	}

	public M setResponseData(java.lang.String responseData) {
		set("responseData", responseData);
		return (M)this;
	}
	
	public java.lang.String getResponseData() {
		return getStr("responseData");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setDatetime(java.util.Date datetime) {
		set("datetime", datetime);
		return (M)this;
	}
	
	public java.util.Date getDatetime() {
		return get("datetime");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setIpCity(java.lang.String ipCity) {
		set("ipCity", ipCity);
		return (M)this;
	}
	
	public java.lang.String getIpCity() {
		return getStr("ipCity");
	}

	public M setTiming(java.lang.Integer timing) {
		set("timing", timing);
		return (M)this;
	}
	
	public java.lang.Integer getTiming() {
		return getInt("timing");
	}

	public M setRoleType(java.lang.Integer roleType) {
		set("roleType", roleType);
		return (M)this;
	}
	
	public java.lang.Integer getRoleType() {
		return getInt("roleType");
	}

	public M setClient(java.lang.String client) {
		set("client", client);
		return (M)this;
	}
	
	public java.lang.String getClient() {
		return getStr("client");
	}

}
