package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysAppversion<M extends BaseSysAppversion<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMajorNo(java.lang.Integer majorNo) {
		set("majorNo", majorNo);
		return (M)this;
	}
	
	public java.lang.Integer getMajorNo() {
		return getInt("majorNo");
	}

	public M setMinorNo(java.lang.Integer minorNo) {
		set("minorNo", minorNo);
		return (M)this;
	}
	
	public java.lang.Integer getMinorNo() {
		return getInt("minorNo");
	}

	public M setRevisionNo(java.lang.Integer revisionNo) {
		set("revisionNo", revisionNo);
		return (M)this;
	}
	
	public java.lang.Integer getRevisionNo() {
		return getInt("revisionNo");
	}

	public M setURL(java.lang.String URL) {
		set("URL", URL);
		return (M)this;
	}
	
	public java.lang.String getURL() {
		return getStr("URL");
	}

	public M setTypes(java.lang.Integer types) {
		set("types", types);
		return (M)this;
	}
	
	public java.lang.Integer getTypes() {
		return getInt("types");
	}

	public M setUpdateContent(java.lang.String updateContent) {
		set("updateContent", updateContent);
		return (M)this;
	}
	
	public java.lang.String getUpdateContent() {
		return getStr("updateContent");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setIsforced(java.lang.Integer isforced) {
		set("isforced", isforced);
		return (M)this;
	}
	
	public java.lang.Integer getIsforced() {
		return getInt("isforced");
	}

	public M setAppType(java.lang.Integer appType) {
		set("appType", appType);
		return (M)this;
	}
	
	public java.lang.Integer getAppType() {
		return getInt("appType");
	}

	public M setPackage(java.lang.String _package) {
		set("package", _package);
		return (M)this;
	}
	
	public java.lang.String getPackage() {
		return getStr("package");
	}

}
