package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysJob<M extends BaseSysJob<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setJobName(java.lang.String jobName) {
		set("job_name", jobName);
		return (M)this;
	}
	
	public java.lang.String getJobName() {
		return getStr("job_name");
	}

	public M setCron(java.lang.String cron) {
		set("cron", cron);
		return (M)this;
	}
	
	public java.lang.String getCron() {
		return getStr("cron");
	}

	public M setStatus(java.lang.Boolean status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public M setClazzPath(java.lang.String clazzPath) {
		set("clazz_path", clazzPath);
		return (M)this;
	}
	
	public java.lang.String getClazzPath() {
		return getStr("clazz_path");
	}

	public M setJobDesc(java.lang.String jobDesc) {
		set("job_desc", jobDesc);
		return (M)this;
	}
	
	public java.lang.String getJobDesc() {
		return getStr("job_desc");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.Integer updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateBy() {
		return getInt("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
