package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysBasicinfo<M extends BaseSysBasicinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSystemName(java.lang.String systemName) {
		set("systemName", systemName);
		return (M)this;
	}
	
	public java.lang.String getSystemName() {
		return getStr("systemName");
	}

	public M setSystemDomain(java.lang.String systemDomain) {
		set("systemDomain", systemDomain);
		return (M)this;
	}
	
	public java.lang.String getSystemDomain() {
		return getStr("systemDomain");
	}

	public M setPortDomain(java.lang.String portDomain) {
		set("portDomain", portDomain);
		return (M)this;
	}
	
	public java.lang.String getPortDomain() {
		return getStr("portDomain");
	}

	public M setPsdCount(java.lang.Integer psdCount) {
		set("psdCount", psdCount);
		return (M)this;
	}
	
	public java.lang.Integer getPsdCount() {
		return getInt("psdCount");
	}

	public M setPsdTime(java.lang.Integer psdTime) {
		set("psdTime", psdTime);
		return (M)this;
	}
	
	public java.lang.Integer getPsdTime() {
		return getInt("psdTime");
	}

	public M setPsdSessionOut(java.lang.Integer psdSessionOut) {
		set("psdSessionOut", psdSessionOut);
		return (M)this;
	}
	
	public java.lang.Integer getPsdSessionOut() {
		return getInt("psdSessionOut");
	}

	public M setAndroidURL(java.lang.String androidURL) {
		set("androidURL", androidURL);
		return (M)this;
	}
	
	public java.lang.String getAndroidURL() {
		return getStr("androidURL");
	}

	public M setIosURL(java.lang.String iosURL) {
		set("iosURL", iosURL);
		return (M)this;
	}
	
	public java.lang.String getIosURL() {
		return getStr("iosURL");
	}

	public M setPicSize(java.math.BigDecimal picSize) {
		set("picSize", picSize);
		return (M)this;
	}
	
	public java.math.BigDecimal getPicSize() {
		return get("picSize");
	}

	public M setPicExt(java.lang.String picExt) {
		set("picExt", picExt);
		return (M)this;
	}
	
	public java.lang.String getPicExt() {
		return getStr("picExt");
	}

	public M setFileSize(java.math.BigDecimal fileSize) {
		set("fileSize", fileSize);
		return (M)this;
	}
	
	public java.math.BigDecimal getFileSize() {
		return get("fileSize");
	}

	public M setFileExt(java.lang.String fileExt) {
		set("fileExt", fileExt);
		return (M)this;
	}
	
	public java.lang.String getFileExt() {
		return getStr("fileExt");
	}

	public M setSmsProvider(java.lang.String smsProvider) {
		set("smsProvider", smsProvider);
		return (M)this;
	}
	
	public java.lang.String getSmsProvider() {
		return getStr("smsProvider");
	}

	public M setSmsTimeout(java.lang.Integer smsTimeout) {
		set("smsTimeout", smsTimeout);
		return (M)this;
	}
	
	public java.lang.Integer getSmsTimeout() {
		return getInt("smsTimeout");
	}

	public M setSmsParameter(java.lang.String smsParameter) {
		set("smsParameter", smsParameter);
		return (M)this;
	}
	
	public java.lang.String getSmsParameter() {
		return getStr("smsParameter");
	}

	public M setWechatId(java.lang.String wechatId) {
		set("wechatId", wechatId);
		return (M)this;
	}
	
	public java.lang.String getWechatId() {
		return getStr("wechatId");
	}

	public M setWechatQrCode(java.lang.String wechatQrCode) {
		set("wechatQrCode", wechatQrCode);
		return (M)this;
	}
	
	public java.lang.String getWechatQrCode() {
		return getStr("wechatQrCode");
	}

	public M setServiceTel(java.lang.String serviceTel) {
		set("serviceTel", serviceTel);
		return (M)this;
	}
	
	public java.lang.String getServiceTel() {
		return getStr("serviceTel");
	}

	public M setEmailHost(java.lang.String emailHost) {
		set("emailHost", emailHost);
		return (M)this;
	}
	
	public java.lang.String getEmailHost() {
		return getStr("emailHost");
	}

	public M setEmailPort(java.lang.Integer emailPort) {
		set("emailPort", emailPort);
		return (M)this;
	}
	
	public java.lang.Integer getEmailPort() {
		return getInt("emailPort");
	}

	public M setEmailUsername(java.lang.String emailUsername) {
		set("emailUsername", emailUsername);
		return (M)this;
	}
	
	public java.lang.String getEmailUsername() {
		return getStr("emailUsername");
	}

	public M setEmailPassword(java.lang.String emailPassword) {
		set("emailPassword", emailPassword);
		return (M)this;
	}
	
	public java.lang.String getEmailPassword() {
		return getStr("emailPassword");
	}

	public M setIp(java.lang.Integer ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public java.lang.Integer getIp() {
		return getInt("ip");
	}

	public M setMac(java.lang.Integer mac) {
		set("mac", mac);
		return (M)this;
	}
	
	public java.lang.Integer getMac() {
		return getInt("mac");
	}

	public M setAliAppId(java.lang.String aliAppId) {
		set("aliAppId", aliAppId);
		return (M)this;
	}
	
	public java.lang.String getAliAppId() {
		return getStr("aliAppId");
	}

	public M setAliPrivateKey(java.lang.String aliPrivateKey) {
		set("aliPrivateKey", aliPrivateKey);
		return (M)this;
	}
	
	public java.lang.String getAliPrivateKey() {
		return getStr("aliPrivateKey");
	}

	public M setAliPublicKey(java.lang.String aliPublicKey) {
		set("aliPublicKey", aliPublicKey);
		return (M)this;
	}
	
	public java.lang.String getAliPublicKey() {
		return getStr("aliPublicKey");
	}

	public M setAliNotifyUTL(java.lang.String aliNotifyUTL) {
		set("aliNotifyUTL", aliNotifyUTL);
		return (M)this;
	}
	
	public java.lang.String getAliNotifyUTL() {
		return getStr("aliNotifyUTL");
	}

}
