package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenubutton<M extends BaseSysMenubutton<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWindowName(java.lang.String windowName) {
		set("windowName", windowName);
		return (M)this;
	}
	
	public java.lang.String getWindowName() {
		return getStr("windowName");
	}

	public M setMenuId(java.lang.Integer menuId) {
		set("menuId", menuId);
		return (M)this;
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menuId");
	}

	public M setButtonId(java.lang.Integer buttonId) {
		set("buttonId", buttonId);
		return (M)this;
	}
	
	public java.lang.Integer getButtonId() {
		return getInt("buttonId");
	}

	public M setButtonUrl(java.lang.String buttonUrl) {
		set("buttonUrl", buttonUrl);
		return (M)this;
	}
	
	public java.lang.String getButtonUrl() {
		return getStr("buttonUrl");
	}

	public M setButtonSaveUrl(java.lang.String buttonSaveUrl) {
		set("buttonSaveUrl", buttonSaveUrl);
		return (M)this;
	}
	
	public java.lang.String getButtonSaveUrl() {
		return getStr("buttonSaveUrl");
	}

	public M setWidth(java.lang.Integer width) {
		set("width", width);
		return (M)this;
	}
	
	public java.lang.Integer getWidth() {
		return getInt("width");
	}

	public M setHeight(java.lang.Integer height) {
		set("height", height);
		return (M)this;
	}
	
	public java.lang.Integer getHeight() {
		return getInt("height");
	}

	public M setOpenMode(java.lang.Integer openMode) {
		set("openMode", openMode);
		return (M)this;
	}
	
	public java.lang.Integer getOpenMode() {
		return getInt("openMode");
	}

	public M setJsFunctionBefore(java.lang.String jsFunctionBefore) {
		set("jsFunctionBefore", jsFunctionBefore);
		return (M)this;
	}
	
	public java.lang.String getJsFunctionBefore() {
		return getStr("jsFunctionBefore");
	}

	public M setJsFunctionAfter(java.lang.String jsFunctionAfter) {
		set("jsFunctionAfter", jsFunctionAfter);
		return (M)this;
	}
	
	public java.lang.String getJsFunctionAfter() {
		return getStr("jsFunctionAfter");
	}

}
