package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysSqlmodel<M extends BaseSysSqlmodel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSql(java.lang.String sql) {
		set("sql", sql);
		return (M)this;
	}
	
	public java.lang.String getSql() {
		return getStr("sql");
	}

	public M setTpl(java.lang.String tpl) {
		set("tpl", tpl);
		return (M)this;
	}
	
	public java.lang.String getTpl() {
		return getStr("tpl");
	}

}
