package io.itman.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysSqlmodel<M extends BaseSysSqlmodel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSql(java.lang.String sql) {
		set("sql", sql);
		return (M)this;
	}
	
	public java.lang.String getSql() {
		return getStr("sql");
	}

	public M setTpl(java.lang.String tpl) {
		set("tpl", tpl);
		return (M)this;
	}
	
	public java.lang.String getTpl() {
		return getStr("tpl");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setDesc(java.lang.String desc) {
		set("desc", desc);
		return (M)this;
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setConnectionId(java.lang.Integer connectionId) {
		set("connectionId", connectionId);
		return (M)this;
	}
	
	public java.lang.Integer getConnectionId() {
		return getInt("connectionId");
	}

	public M setGroovy(java.lang.String groovy) {
		set("groovy", groovy);
		return (M)this;
	}
	
	public java.lang.String getGroovy() {
		return getStr("groovy");
	}

}
